version: "3"
services:
  web:
    build: ./docker/web
    ports:
      - 8000:80
    volumes:
      - ./www:/var/www
      - ./docker/web/php.ini:/usr/local/etc/php/conf.d/php.ini
      - ./log:/var/log
    environment:
      TZ: Asia/Tokyo
      MY_DB_HOST: db:3306
      MY_DB_NAME: my_database
      MY_DB_USER: my_user
      MY_DB_PASSWORD: my_pass
    depends_on:
      - db

  db:
    image: mysql:5.7
    volumes:
      - ./docker/db/mysql:/var/lib/mysql
    environment:
      TZ: Asia/Tokyo
      MYSQL_ROOT_PASSWORD: root_pass
      MYSQL_DATABASE: my_database
      MYSQL_USER: my_user
      MYSQL_PASSWORD: my_pass

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - 8080:80
    environment:
      TZ: Asia/Tokyo
    depends_on:
      - db

  mailhog:
    image: mailhog/mailhog
    ports:
      - 1025:1025
      - 8025:8025
    environment:
      TZ: Asia/Tokyo
